import "MediumSelector.idl";

namespace NearbyLibrary
{
    enum Strategy
    {
        None,
        P2pCluster,
        P2pStar,
        P2pPointToPoint,
    };

    [default_interface]
    runtimeclass ConnectionOptions 
    {
        Strategy Strategy;
        MediumSelector Allowed;
        Boolean AutoUpgradeBandwidth;
        Boolean EnforceTopologyConstraints;
        Boolean LowPower;
        Boolean EnableBluetoothListening;
        Boolean EnableWebrtcListening;
        Boolean IsOutOfBandConnection;
        String RemoteBluetoothMacAddress;
        String FastAdvertisementServiceUuid;
        Int32 KeepAliveIntervalMillis;
        Int32 KeepAliveTimeoutMillis;
        Boolean Empty{ get; };

        ConnectionOptions();
        void Clear();
    }
}
