import "BaseEventArgs.idl";

namespace NearbyLibrary
{
    [default_interface]
    runtimeclass ConnectionDisconnectedEventArgs : BaseEventArgs
    {
        ConnectionDisconnectedEventArgs(String endpointId);
    }
}
