namespace NearbyLibrary
{
    runtimeclass ConnectionResponseInfo
    {
        ConnectionResponseInfo();
        
        String RemoteEndpointInfo;
        String AuthenticationToken;
        String AuthenticationDigits;
        Boolean IsIncomingConnection;
        Boolean IsConnectionVerified;
    }
}
