import "BaseEventArgs.idl";

namespace NearbyLibrary
{
    [default_interface]
    runtimeclass ConnectionAcceptedEventArgs : BaseEventArgs
    {
        ConnectionAcceptedEventArgs(String endpointId);
    }
}
