namespace NearbyLibrary
{
    enum Medium
    {
        UnknownMedium,
        Mdns, // PROTOBUF_DEPRECATED_ENUM
        Bluetooth,
        WifiHotspot,
        Ble,
        WifiLan,
        WifiAware,
        Nfc,
        WifiDirect,
        WebRtc,
        BleL2cap
    };

    [default_interface]
    runtimeclass OutOfBandConnectionMetadata 
    {
        OutOfBandConnectionMetadata();
        Medium Medium;
        String EndpointId;
        String EndpointInfo;
        String RemoteBluetoothMacAddress;
    }
}
