namespace NearbyLibrary
{
    enum StatusState
    {
        Success,
        Error,
        OutOfOrderApiCall,
        AlreadyHaveActiveStrategy,
        AlreadyAdvertising,
        AlreadyDiscovering,
        EndpointIoError,
        EndpointUnknown,
        ConnectionRejected,
        AlreadyConnectedToEndpoint,
        NotConnectedToEndpoint,
        BluetoothError,
        BleError,
        WifiLanError,
        PayloadUnknown,
    };

    [default_interface]
    runtimeclass Status 
    {
        StatusState Value;

        Status();
        Status(StatusState status);
        Boolean Ok{ get; };
    }
}
