cc_library(
    name = "logging",
    hdrs = ["check.h"],
    include_prefix = "base",
    visibility = ["//platform:__subpackages__"],
)

cc_library(
    name = "stringprintf",
    srcs = ["stringprintf.cc"],
    hdrs = ["stringprintf.h"],
    include_prefix = "base",
    visibility = ["//platform:__subpackages__"],
)