cc_binary(
    name = "nearby",
    srcs = [
        "framework.h",
        "dllmain.cpp",
        "interop.h",
        "interop.cpp",
    ],
    deps = [
        "//core:core",
        "//platform/impl/windows:windows",
    ],
    linkshared = True,
)